### PR TITLE
vari-bbc/rnaseq_workflow updates

### PR DESCRIPTION
**Pull request by RFillinger**
Changes to this code will do 3 things: 

1) Automatically add read groups to `units_template.tsv` if, and only if, submitted fastq file headers don't include adequate infomration. This will not add read groups for files with adequate read groups. 

2) make_sce.R rule wasn't quite functioning properly for outputting the results into the SummarizedExperiment folder used for downstream analysis. I just added an if statement in make_sce.R to check that the SummarizedExperiment folder was made and to make it if not already built.

3) I added the ability to select organism references by changing the organism name in config.yaml rather than copy-pasting paths to each required reference file for a given organism. Right now, you can select human, mouse, fly, or worm references and I just added an "other" category that can be filled out for whatever reference may be needed.

### CODE REVIEW

**Comment by genomics-kl** [comment]
With regards to #2, I cannot reproduce your issue. Please see the `rnaseq_workflow` folder in our projects folder on the HPC, where I just ran the workflow to completion using an example dataset. Could you please provide instructions/data to reproduce your error?

I have not had a chance to look at your code for #1 and #3 but will do so when I get back.

**Comment by RFillinger** [comment]
Do you have a file path to the rnaseq_workflow directory you're referring to? I am searching in /varidata/research/projects/bbc, but I haven't found it. 

It happens when I start a project from scratch. I'll replicate it and save the error report, and direct you to where it's happening.

**Comment by genomics-kl** [comment]
It’s the folder with all our projects.

**Comment by genomics-kl** [comment]
Hi Bobby. Sorry for the delay in getting to this. Today, I ran into the same issue you did when you ran files from the SRA. I have fixed the issue in cbaeb835. Can you please see if `read_groups.py` is still needed?

**Comment by genomics-kl** [comment]
> Changes to this code will do 3 things:
> 
> 1. Automatically add read groups to `units_template.tsv` if, and only if, submitted fastq file headers don't include adequate infomration. This will not add read groups for files with adequate read groups.
> 2. make_sce.R rule wasn't quite functioning properly for outputting the results into the SummarizedExperiment folder used for downstream analysis. I just added an if statement in make_sce.R to check that the SummarizedExperiment folder was made and to make it if not already built.
> 3. I added the ability to select organism references by changing the organism name in config.yaml rather than copy-pasting paths to each required reference file for a given organism. Right now, you can select human, mouse, fly, or worm references and I just added an "other" category that can be filled out for whatever reference may be needed.

Just wanted to circle back to the original goals  of this PR:

1. Obviated by cbaeb83. I prefer editing/fixing the existing code rather than adding another script and having to parse through the fastq headers twice.
2. This issue was not reproducible.
3. I like the idea for this. Is there a way to move the file paths from the config file to a separate YAML file? The current implementation makes the config file very bloated, and I imagine that it will get more bloated as we add more references (new genome builds or new strains for example).

**Comment by RFillinger** [comment]
1) That's the better approach. 
2) This bug had to deal with file permissions. It was in a Teams thread somewhere.
3) I like your idea about bloating the config file with organisms. I'll patch in a YAML file with organisms.

**Comment by genomics-kl** [comment]
2. There was indeed an issue with permissions, but I'm pretty sure your specific issue was due to incorrect filling of the samplesheet. See screenshot below of the thread you are referring to.

image

**Comment by RFillinger** [comment]
Got'cha! I thought you were referring to the old issue with #2.

**Comment by genomics-kl** [comment]
This will be addressed by changes proposed in our internal 'hackathon'.

**Pull request closed without merging**
