### PR TITLE
Migrate to Snakemake 8

### PR DESCRIPTION
**Pull request by dfbautista**
The new module for Snakemake (8.25.2) has the plugin cluster-generic. It offers the same functionality of the --cluster flag that we use to submit jobs in run_snake.sh. I don't see any incompatibility between the versions apart from this.

### CODE REVIEW

**Comment by genomics-kl** [comment]
Awesome. Did you do a full run using old data with Snakemake 8.25.2?

**Comment by dfbautista** [comment]
Yes, I ran the samples from the `units.tsv` template. The logs were the same, but we might want to start generating unit tests before merging all the PRs. There is support from Snakemake to automatically use this [here.](https://snakemake.readthedocs.io/en/stable/snakefiles/testing.html)

**Comment by genomics-kl** [comment]
If I'm understanding correctly, the steps would be:

1) Make some small fastq files for testing.
2) Run the workflow.
3) Run `snakemake --generate-unit-tests` to generate the tests which will be stored in `.tests/unit/`.
4) Make changes to code.
5) Run `pytest .tests/unit/` to check if the results have changed.
6) If changed results are expected, then run `snakemake --generate-unit-tests` again to update the unit tests.

If/When you have the bandwidth, it would be great if you could put together an "SOP" and give us a short demo.

**Comment by genomics-kl** [comment]
Hey Daniel. Thanks for making these changes. I think they all look good. But, I just thought of something. Could you add a new file named `bin/run_snakemake_v7.sh` containing the old script in case there are issues with the Snakemake 8 one? Otherwise, please merge once you've finished testing.

**Pull request merged**
